version: "3.8"

services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    volumes:
      - ./configs/postgres:/docker-entrypoint-initdb.d
      -  db_data:/var/lib/postgresql/data

    ports:
      - 5432:5432
    networks:
      - forum_network
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${DBS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    depends_on:
      - db
    networks:
      - forum_network
networks:
  forum_network:
volumes:
  db_data:
  pgadmin_data:
