# Generated by Django 4.2.3 on 2025-02-12 11:15

import django.core.validators
from django.db import migrations, models
import images.models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_profileimage_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileimage",
            name="cropped_image_path",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=images.models.cropped_image_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpeg", "png", "jpg"]
                    )
                ],
            ),
        ),
    ]
