# Generated by Django 4.2.3 on 2025-01-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0005_contactinformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
